{
  "hash": "507d48cfcd317b76aaf4b930b6eed18b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"RNA-Seq differential expression analysis\"\nsubtitle: \"Week 4 lab\"\ndate: 2026-02-06\nauthor:\n  - name: Jelmer Poelstra\n    orcid: 0000-0002-3514-7462\n    email: poelstra.1@osu.edu\n    affiliation: \n      - name: CFAES Bioinformatics Core, Ohio State University\n        url: https://mcic.osu.edu/bioinformatics\nother-links:\n  - text: \"Week 4 lecture\"\n    icon: bookmarks\n    href: rnaseq.html\n  - text: \"R homework\"\n    icon: code\n    href: r_homework.html\nexecute: \n  eval: true\n  cache: false\nknitr:\n  opts_chunk:\n    out.width: \"85%\"\n    class-output: styled-output\nproject:\n  execute-dir: project\neditor_options: \n  chunk_output_type: console\nbibliography: ../references.bib\n---\n\n\n\n\n------\n\n<br>\n\n## Introduction\n\n### Recap\n\n[**Last week**](data.qmd), you explored the RNA-Seq reads from @garrigós2025\nand the *Culex pipiens* reference genome files.\n\nIn [**yesterday's lecture**](rnaseq.qmd),\nyou learned about the steps to generate a gene count table from this input data:\n\n1. **Read preprocessing**: QC, trimming, and optionally rRNA removal\n2. **Alignment** of reads to a reference genome (+ alignment QC)\n3. **Quantification** of expression levels\n\n### Today's goals\n\nI have performed the above steps for you already,\nand you will start with the output of step 3: a **gene count table**.\nWith that gene count table, you will:\n\n- Create an R object that also incorporates the meta (sample) data\n- Perform exploratory data analysis including a PCA\n- Run a Differential Expression (DE) analysis\n- Extract and visualize the DE results\n\n## Getting set up\n\n### Start an RStudio session at OSC\n\nStart an RStudio session at OSC like we did last week and like you did for this\nweek's homework:\n\n1. Log in to OSC at <https://ondemand.osc.edu>\n2. Click on **`Interactive Apps`** (top bar) and then **`RStudio Server`**\n   (all the way at the bottom)\n3. Fill out the form as follows:\n   - Cluster: **`Pitzer`**\n   - R version: **`4.4.0`**\n   - Project: **`PAS2880`**\n   - Number of hours: **`4`**\n   - Node type: **`any`**\n   - Number of cores: **`2`**\n4. Click the big blue **`Launch`** button at the bottom\n5. Now, you should be sent to a new page with a box at the top for your\n   RStudio Server \"job\", which should initially be \"Queued\" (waiting to start).\n6. Your job should start running very soon,\n   with the top bar of the box turning green and saying \"Running\".\n7. Click **`Connect to RStudio Server`** at the bottom of the box,\n   and an RStudio Server instance will open in a new browser tab.\n   You're ready to go!\n\n### Create an R script\n\nToday, you're going to write most of your code in an R script instead of typing\nit directly in the R console, as explained in the [R homework](r_homework.qmd):\n\n1. Create and open a new R script by clicking\n   **`File`** (top menu bar) \\> **`New File`** \\> **`R Script`**.\n\n2. Save this new script right away by clicking **`File`** \\> **`Save As`**.\n   In the dialog box,\n   you can save it right in the suggested folder (which is your OSC Home folder),\n   or you can make a new folder for this course by clicking \"New Folder\" in\n   the bottom left.\n   Regardless, save the script as **`lab4_DE.R`**\n   (the extension for R scripts is `.R`).\n\n### Load the R packages you will use\n\nAs part of your homework, you installed a few R packages with functionality\nyou'll need in today's lab.\n\nRecall that R packages behave equivalently to other software/apps,\nin that installation is a one-time thing,\nbut you need to lead them in any given session to use them.\nLet's start with that:\n\n::: {.callout-important appearance=\"simple\"}\nHere, and with all the code in this lab,\ntype or copy it in your script, and send it to the console from there.\nRecall that you can send code to the console by pressing\n<kbd>**Ctrl**</kbd> **+** <kbd>**Enter**</kbd> on Windows,\nor <kbd>Cmd</kbd> + <kbd>Return</kbd> on a Mac.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Then, load the R packages:\nlibrary(DESeq2)          # Differential expression analysis\nlibrary(EnhancedVolcano) # Volcano plot\nlibrary(tidyverse)       # Misc. data manipulation and plotting\n```\n:::\n\n\n\n\nRunning the code above will produce output in the R console, and some of it in orange,\nbut all should be good unless you see explicit errors at the bottom.\n\n<details><summary>*Click to see expected output*</summary>\n\n<hr style=\"height:1pt; visibility:hidden;\" />\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.1     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(DESeq2)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\nLoading required package: S4Vectors\nLoading required package: stats4\nLoading required package: BiocGenerics\nLoading required package: generics\n\nAttaching package: 'generics'\n\nThe following object is masked from 'package:lubridate':\n\n    as.difftime\n\nThe following object is masked from 'package:dplyr':\n\n    explain\n\nThe following objects are masked from 'package:base':\n\n    as.difftime, as.factor, as.ordered, intersect, is.element, setdiff,\n    setequal, union\n\n\nAttaching package: 'BiocGenerics'\n\nThe following object is masked from 'package:dplyr':\n\n    combine\n\nThe following objects are masked from 'package:stats':\n\n    IQR, mad, sd, var, xtabs\n\nThe following objects are masked from 'package:base':\n\n    anyDuplicated, aperm, append, as.data.frame, basename, cbind,\n    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,\n    get, grep, grepl, is.unsorted, lapply, Map, mapply, match, mget,\n    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,\n    rbind, Reduce, rownames, sapply, saveRDS, table, tapply, unique,\n    unsplit, which.max, which.min\n\n\nAttaching package: 'S4Vectors'\n\nThe following objects are masked from 'package:lubridate':\n\n    second, second<-\n\nThe following objects are masked from 'package:dplyr':\n\n    first, rename\n\nThe following object is masked from 'package:tidyr':\n\n    expand\n\nThe following object is masked from 'package:utils':\n\n    findMatches\n\nThe following objects are masked from 'package:base':\n\n    expand.grid, I, unname\n\nLoading required package: IRanges\n\nAttaching package: 'IRanges'\n\nThe following object is masked from 'package:lubridate':\n\n    %within%\n\nThe following objects are masked from 'package:dplyr':\n\n    collapse, desc, slice\n\nThe following object is masked from 'package:purrr':\n\n    reduce\n\nLoading required package: GenomicRanges\nLoading required package: GenomeInfoDb\nLoading required package: SummarizedExperiment\nLoading required package: MatrixGenerics\nLoading required package: matrixStats\n\nAttaching package: 'matrixStats'\n\nThe following object is masked from 'package:dplyr':\n\n    count\n\n\nAttaching package: 'MatrixGenerics'\n\nThe following objects are masked from 'package:matrixStats':\n\n    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,\n    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,\n    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,\n    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,\n    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,\n    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,\n    colWeightedMeans, colWeightedMedians, colWeightedSds,\n    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,\n    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,\n    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,\n    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,\n    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,\n    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,\n    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,\n    rowWeightedSds, rowWeightedVars\n\nLoading required package: Biobase\nWelcome to Bioconductor\n\n    Vignettes contain introductory material; view with\n    'browseVignettes()'. To cite Bioconductor, see\n    'citation(\"Biobase\")', and for packages 'citation(\"pkgname\")'.\n\n\nAttaching package: 'Biobase'\n\nThe following object is masked from 'package:MatrixGenerics':\n\n    rowMedians\n\nThe following objects are masked from 'package:matrixStats':\n\n    anyMissing, rowMedians\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(EnhancedVolcano)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\nLoading required package: ggrepel\n```\n\n\n:::\n:::\n\n\n\n\n</details>\n\n## Create a DESeq2 object\n\nLike in @garrigós2025,\nyou'll perform a Principal Component Analysis (PCA) and a\nDifferential Expression (DE) analysis.\nTo do so, you'll use the **DESeq2** R package (@love2014deseq2, \n[website](https://bioconductor.org/packages/release/bioc/html/DESeq2.html)).\n\nDESeq2 has its own \"object type\" (a specific R format type) and\nbefore you can do anything else,\nyou need to create a DESeq2 object from three components:\n\n1. **Sample metadata**\\\n   This table should contain information on which samples belong to which groups\n   that should be compared (i.e., the experiment's \"independent variables\").\n2. **Count table**\\\n   A table with one row per gene, and one column per sample.\n3. **A statistical design**\\\n   A statistical design formula to tell DESEq2 which groups to compare\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n### Sample metadata\n\nFirst, you'll load the sample metadata from the same file you saw last week.\nTo do so, use the `read_tsv()` function you also saw in the homework --\nthis reads a TSV (Tab-Separated Values) file into a dataframe:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeta_raw <- read_tsv(\"/fs/scratch/PAS2880/ENT6703/data/meta/metadata.tsv\")\n```\n:::\n\n\n\n\nLet's take a look at the resulting dataframe with the `View()` function:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# View() will open the dataframe in a spreadsheet like view\nView(meta_raw)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n# A tibble: 22 × 3\n   sample_id     dpi treatment  \n   <chr>       <dbl> <chr>      \n 1 ERR10802864     1 cathemerium\n 2 ERR10802867     1 cathemerium\n 3 ERR10802870     1 cathemerium\n 4 ERR10802866     1 control    \n 5 ERR10802869     1 control    \n 6 ERR10802863     1 control    \n 7 ERR10802871     1 relictum   \n 8 ERR10802874     1 relictum   \n 9 ERR10802865     1 relictum   \n10 ERR10802868     1 relictum   \n11 ERR10802882    10 cathemerium\n12 ERR10802875    10 cathemerium\n13 ERR10802879    10 cathemerium\n14 ERR10802883    10 cathemerium\n15 ERR10802878    10 control    \n16 ERR10802884    10 control    \n17 ERR10802877    10 control    \n18 ERR10802881    10 control    \n19 ERR10802876    10 relictum   \n20 ERR10802880    10 relictum   \n21 ERR10802885    10 relictum   \n22 ERR10802886    10 relictum   \n```\n\n\n:::\n:::\n\n\n\n\n::: exercise\n#### {{< fa user-edit >}} Exercise: Interpret the metadata\n\nBased on the information in the table, try to understand the experimental design.\nHow many timepoints and treatments are there?\nHow many biological replicates?\n\n<details><summary>*Click to see the solution*</summary>\n\n- The `dpi` column has the number of Days Post Infection\n  (i.e., timepoints): either 1 or 10 days.\n  \n- The `treatment` column contains the treatment:\n  which *Plasmodium* species, or \"control\" (not infected).\n\n- All in all, there are 3 treatments across each of 2 timepoints,\n  with 3-4 replicates per treatment-timepoint combination.\n</details>\n:::\n\n<hr style=\"height:1pt; visibility:hidden;\" />\n\nYou'll now have to make some modifications to the metadata table\nso that it can be used in DESeq2:\n\n- The table should be sorted by sample ID:\n  you can use the `arrange()` function to do so\n- The sample IDs should be row names, not a separate column:\n  we can use the `column_to_rownames()` function for this\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The input is the raw metadata dataframe ('meta_raw'),\n# and we'll store the output in a new, processed dataframe ('meta'):\nmeta <- meta_raw |>\n  # By converting 'treatment' columns into a \"factor\",\n  # you can provide a custom order that will be respected in the plot -\n  # this, way 24h comes before 10d, and control before the two infections.\n  mutate(\n    dpi = factor(dpi, levels = c(1, 10)),\n    treatment = factor(treatment, levels = c(\"control\", \"cathemerium\", \"relictum\"))\n  ) |>\n  # 1. Sort the table by 'sample_id' column:\n  arrange(sample_id) |>\n  # 2. Turn the 'sample_id' column into row names:\n  column_to_rownames(\"sample_id\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Take a look at the first 6 rows\nhead(meta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n            dpi   treatment\nERR10802863   1     control\nERR10802864   1 cathemerium\nERR10802865   1    relictum\nERR10802866   1     control\nERR10802867   1 cathemerium\nERR10802868   1    relictum\n```\n\n\n:::\n:::\n\n\n\n\nIn the two outputs above,\nnote the difference between having the sample IDs as a separate column versus\nas row names.\nThis is a minor and uninteresting technical difference,\nbut DESeq2 simply expects the sample IDs to be row names.\n\n::: {.callout-note appearance=\"simple\"}\nWhen analyzing data sets, such modifications (\"data wrangling\") are quite common\nand can take up more time and space than the actual analysis itself.\nWhich is one reason we're including these steps in the lab.\n:::\n\n### Count table\n\nI produced a gene count table for you by running the \n[nf-core rnaseq pipeline](https://nf-co.re/rnaseq)\non the input data you saw last week (FASTQ reads and reference genome files).\n  \nLoad this count table into R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount_df <- read_tsv(\"/fs/scratch/PAS2880/ENT6703/results/counts.tsv\")\n```\n:::\n\n\n\n\nTake a look at the first 6 rows:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(count_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n# A tibble: 6 × 24\n  gene_id gene_name ERR10802863 ERR10802864 ERR10802865 ERR10802866 ERR10802867\n  <chr>   <chr>           <dbl>       <dbl>       <dbl>       <dbl>       <dbl>\n1 ATP6    ATP6         10275.       8255.       4103.      18615.      11625.  \n2 ATP8    ATP8             3.85        2.92        2.33        7.76        7.01\n3 COX1    COX1         88041.      83394.      36975.     136054.     130863.  \n4 COX2    COX2          8749.       7925.       2901.      16802.      10026.  \n5 COX3    COX3         55772.      50312.      35074.      80510.      69850.  \n6 CYTB    CYTB         38543.      36352.      22185.      62147.      57461.  \n# ℹ 17 more variables: ERR10802868 <dbl>, ERR10802869 <dbl>, ERR10802870 <dbl>,\n#   ERR10802871 <dbl>, ERR10802874 <dbl>, ERR10802875 <dbl>, ERR10802876 <dbl>,\n#   ERR10802877 <dbl>, ERR10802878 <dbl>, ERR10802879 <dbl>, ERR10802880 <dbl>,\n#   ERR10802881 <dbl>, ERR10802882 <dbl>, ERR10802883 <dbl>, ERR10802884 <dbl>,\n#   ERR10802885 <dbl>, ERR10802886 <dbl>\n```\n\n\n:::\n:::\n\n\n\n\nHere, too, we have to make several modifications --\nDESeq2 expects that the count table:\n\n- Has gene IDs as row names\n- Does not contain any non-numeric columns\n- Contains integer (whole-number, rounded) values\n- Is a \"matrix\", a slighly different object type from a dataframe\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount_mat <- count_df |>\n  # 1. Turn the 'gene_id' column into row names:\n  column_to_rownames(\"gene_id\") |>\n  # 2. Remove a remaining non-numeric column (which has gene names):\n  select(-gene_name) |>\n  # 3. Round everything to whole numbers:\n  round() |>\n  # 4. Convert it to a formal 'matrix' format:\n  as.matrix()\n```\n:::\n\n\n\n\nLet's once again take a look at the first 6 rows:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(count_mat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n     ERR10802863 ERR10802864 ERR10802865 ERR10802866 ERR10802867 ERR10802868\nATP6       10275        8255        4103       18615       11625        7967\nATP8           4           3           2           8           7           2\nCOX1       88041       83394       36975      136054      130863       62279\nCOX2        8749        7925        2901       16802       10026        6701\nCOX3       55772       50312       35074       80510       69850       42478\nCYTB       38543       36352       22185       62147       57461       28159\n     ERR10802869 ERR10802870 ERR10802871 ERR10802874 ERR10802875 ERR10802876\nATP6       12788        4408       13648       13834        1346       10032\nATP8           2           0           2           1           3           2\nCOX1      109596      106402      104394       77682       38276       78290\nCOX2       11494        6603       11151        9893        1473       13146\nCOX3       68228       71945       66900       52368       14665       37275\nCYTB       46219       52035       46090       35247       17449       38762\n     ERR10802877 ERR10802878 ERR10802879 ERR10802880 ERR10802881 ERR10802882\nATP6         987        1834        3337        5036        1983       11586\nATP8           0           0           0           3           0          27\nCOX1       17785       32099       64490       63960       50965       76113\nCOX2        1141        1907        3439        8334        2063       12752\nCOX3        8797       15948       26278       29997       17802       35419\nCYTB       11177       22262       34368       33401       25854       43912\n     ERR10802883 ERR10802884 ERR10802885 ERR10802886\nATP6       18821        2792       11749        6682\nATP8          40           0           8           1\nCOX1      108343       65829      107741       94682\nCOX2       19148        2713       17947       10656\nCOX3       51441       24915       50029       47750\nCYTB       57844       34616       50587       51198\n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Bonus: Check that the sample IDs match _(Click to expand)_\nWhen creating the DESeq2 object,\nDESeq2 assumes that sample IDs in the metadata and count tables completely match\n(no extra/missing samples in either table), and are provided in the same order.\nLet's make sure this is indeed the case:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall(rownames(meta) == colnames(count_mat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Create the DESeq2 object\n\nYou will create the DESeq2 object using the function `DESeqDataSetFromMatrix()`,\nwhich requires three arguments corresponding to the components discussed above:\n\n- The metadata with argument **`colData`**.\n- The count data with argument **`countData`**.\n- The statistical design for the DE analysis with argument **`design`**.\n  For now, you will specify **`~1`**,\n  which effectively means \"no design\" ---\n  you will change this before the actual DE analysis.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# (`dds` is a name commonly used for DESeq2 objects, short for \"DESeq Data Set\")\ndds <- DESeqDataSetFromMatrix(\n  colData = meta,\n  countData = count_mat,\n  design = ~ 1\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\nconverting counts to integer mode\n```\n\n\n:::\n:::\n\n\n\n\nBefore running the differential expression analysis, though,\nlet's do a bit of exploratory data analysis.\n\n## Exploratory Data Analysis\n\n### The count table\n\nWhat are the number of rows (=number of genes) and columns (=number of samples)\nof your gene expression count matrix?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(count_mat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] 18855    22\n```\n\n\n:::\n:::\n\n\n\n\nSo, we have 18855 genes and 22 samples.\n\nHow do the \"library sizes\", i.e. the summed per-sample gene counts,\ncompare across samples?\nTo see this, you can compute column sums (recall: columns are samples) using\nthe `colSums()` function:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(count_mat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\nERR10802863 ERR10802864 ERR10802865 ERR10802866 ERR10802867 ERR10802868 \n   24297245    17177436    22745445    26849403    21471477    17506262 \nERR10802869 ERR10802870 ERR10802871 ERR10802874 ERR10802875 ERR10802876 \n   24299398    25490128    26534405    22194841    18927885    28804150 \nERR10802877 ERR10802878 ERR10802879 ERR10802880 ERR10802881 ERR10802882 \n    9498249    14807513    20667093    23107463    17545375    19088206 \nERR10802883 ERR10802884 ERR10802885 ERR10802886 \n   21418234    19420046    24367372    25452228 \n```\n\n\n:::\n:::\n\n\n\n\nOK, that looks like a lot, but is not so easy to read / interpret.\nLet's convert these numbers:\n\n- To whole millions: divide by 1,000,000 and round (`round()`) the result\n- Sorted from low to high (`sort()`)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(round(colSums(count_mat) / 1000000))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\nERR10802877 ERR10802878 ERR10802864 ERR10802868 ERR10802881 ERR10802875 \n          9          15          17          18          18          19 \nERR10802882 ERR10802884 ERR10802867 ERR10802879 ERR10802883 ERR10802874 \n         19          19          21          21          21          22 \nERR10802865 ERR10802880 ERR10802863 ERR10802869 ERR10802885 ERR10802870 \n         23          23          24          24          24          25 \nERR10802886 ERR10802866 ERR10802871 ERR10802876 \n         25          27          27          29 \n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n#### Bonus: How many genes have non-zero counts? _(Click to expand)_\n\nHow many genes have total (= across all samples) counts that are non-zero?\n\nTo compute this, you can:\n\n- Use `rowSums()` to compute total counts per gene (rows are genes)\n- Subset the count matrix with `[ ]` to only those genes with total counts > 0\n- Count the number of rows in that subsetted matrix with `nrow()`\n\nAll in one line:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(count_mat[rowSums(count_mat) > 0, ])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] 17788\n```\n\n\n:::\n:::\n\n\n\n\n<hr style=\"height:1pt; visibility:hidden;\" />\n\n<details><summary>Your turn: How many genes have total counts of at least 10? *(Click to see the solution)*</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(count_mat[rowSums(count_mat) >= 10, ])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] 16682\n```\n\n\n:::\n:::\n\n\n\n</details>\n\n<details><summary>Your turn: How many genes have *mean* counts of at least 10? *(Click to see the solution)*</summary>\n\nNow you need to divide by the number of samples.\nThis is the number of columns, which you can get with `ncol()`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(count_mat[rowSums(count_mat) / ncol(count_mat) >= 10, ])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] 12529\n```\n\n\n:::\n:::\n\n\n\n</details>\n:::\n\n### Principal Component Analysis (PCA)\n\nYou will now run a PCA to look for overall patterns of (dis)similarity among samples.\nThis will help answer questions like:\n\n- Do the samples cluster by treatment (infection status) and/or time point?\n- Which of these two variables has a greater effect on overall patterns of gene expression?\n- Is there an overall *interaction* between these two variables?\n\nFirst, you have to normalize the count data to account for differences in\nlibrary size among samples and to \"stabilize\" the variance among genes[^4]:\n\n[^4]: Specifically, the point is to remove the correlation among genes between the\n      mean expression level and the variance in expression.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds_vst <- varianceStabilizingTransformation(dds)\n```\n:::\n\n\n\n\nThe authors of the study did this as well:\n\n> *We carried out a Variance Stabilizing Transformation (VST) of the counts to represent the samples on a PCA plot.*\n\nNext, you can run and plot the PCA with a single function call,\n`plotPCA` from DESeq2:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# With 'intgroup', you specify the variables (columns) to color samples by\nplotPCA(dds_vst, intgroup = c(\"dpi\", \"treatment\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\nusing ntop=500 top features by variance\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n``` warning-r-output\nWarning: `aes_string()` was deprecated in ggplot2 3.0.0.\nℹ Please use tidy evaluation idioms with `aes()`.\nℹ See also `vignette(\"ggplot2-in-packages\")` for more information.\nℹ The deprecated feature was likely used in the DESeq2 package.\n  Please report the issue to the authors.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-22-1.png){width=85%}\n:::\n:::\n\n\n\n\n::: exercise\n#### {{< fa user-edit >}} Exercise: Interpret the PCA result\n\n1. Based on the above PCA plot, try to answer the three questions asked at the\n   beginning of this PCA section.\n\n2. How does your plot compare to the PCA plot in the paper (Figure 1),\n   in terms of the conclusions you drew in the previous question?\n\n   <details><summary>*Click to see the paper's Figure 1*</summary>\n   <hr style=\"height:1pt; visibility:hidden;\" />\n  \n   ![](../img/garrigo_PCA.jpeg){fig-align=\"center\" width=\"90%\"}\n  \n   <hr style=\"height:1pt; visibility:hidden;\" />\n   </details>\n:::\n\n::: exercise\n#### {{< fa user-edit >}} Bonus exercise 1: Number of genes in the PCA\n\nBy default, the PCA run by `plotPCA()` does not summarize the variation\nin _all_ genes, but only in the top 500 most variable genes.\nThis tends to be a good representation of overall patterns,\nbut it can be a good idea to check how robust the results are to this choice.\n\nThe `plotPCA()` function has an argument to change the number of included genes.\n\n1. Figure out what the name of this argument is by check the help for the function.\\\n   _(Hint: run `?plotPCA` in the R console)_\n\n2. Play around with different numbers of included genes\n   (e.g., 100, 1000, all genes), and see how this affects the PCA plot.\n\n**TODO - ADD SOLUTION**\n:::\n\n::: exercise\n#### {{< fa user-edit >}} Bonus exercise 2: Make a better PCA plot\n\nCustomize the PCA plot to make it better-looking and clearer.\n\nFor example, in the plot we made above,\neach combination of time point and treatment has a distinct color.\nBut it would be better to use **point color** only to distinguish one of the variables,\nand **point shape** to distinguish the other variable,\nas was done in the paper's Fig. 1.\n\nFirst, you'll need to get the data in a format that you can use to build the plot from scratch.\nYou can do this by using the `returnData = TRUE` argument of the `plotPCA()` function\n(check the first solution below for more details if needed).\n\nThen, the plot customization will require some knowledge of _ggplot2_.\nIf you don't know how to do this yet,\nyou can also try to use generative AI (Microsoft Copilot, ChatGPT, etc.)\nto help you write the code.\n\n<details><summary>*Partial solution: getting the dataframe*</summary>\n\nTo be able to customize the plot properly,\nit's best to build it from scratch ourselves,\nrather than using the `plotPCA` function.\nBut then how do we get the input data in the right shape?\n\nA nice trick is that we can use `returnData = TRUE` in the `plotPCA` function,\nto get plot-ready formatted data instead of an actual plot:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_df <- plotPCA(\n  dds_vst,\n  ntop = 500,\n  intgroup = c(\"dpi\", \"treatment\"),\n  returnData = TRUE\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\nusing ntop=500 top features by variance\n```\n\n\n:::\n:::\n\n\n\n\n</details>\n\n<details><summary>*Click to see a possible solution*</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_df |>\n  ggplot(aes(x = PC1, y = PC2, color = treatment, shape = dpi)) +\n  geom_point(size = 5) +\n  scale_color_brewer(palette = \"Dark2\", name = \"Infection status\") +\n  scale_shape(name = \"Time points\") +\n  theme_bw() +\n  theme(panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-24-1.png){width=85%}\n:::\n:::\n\n\n\n\nLet's improve this plot in two ways:\n\n1. Adding the percentage of variance explained by each principal component to\n   the axes labels.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First extract and store the percentage of variance explained by different\n# principal components, so you can later add this information to the plot:\npct_var <- round(100 * attr(pca_df, \"percentVar\"), 1)\npct_var\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] 85.3  3.1\n```\n\n\n:::\n\n```{.r .cell-code}\npca_df |> \n  ggplot(aes(x = PC1, y = PC2, color = treatment, shape = dpi)) +\n  geom_point(size = 5) +\n  labs(\n    x = paste0(\"PC1 (\", pct_var[1], \"%)\"),\n    y = paste0(\"PC2 (\", pct_var[2], \"%)\")\n    ) +\n  scale_color_brewer(palette = \"Dark2\", name = \"Infection status\") +\n  scale_shape(name = \"Time points\") +\n  theme_bw() +\n  theme(panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-25-1.png){width=85%}\n:::\n:::\n\n\n\n\n2. Improving the order of the legend items: 24 hours should come before 10 days,\n   and the control treatment is best presented first.\n   \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First, modify the factor levels in the PCA dataframe:\npca_df |>\n  ggplot(aes(x = PC1, y = PC2, color = treatment, shape = dpi)) +\n  geom_point(size = 5) +\n  labs(\n    x = paste0(\"PC1 (\", pct_var[1], \"%)\"),\n    y = paste0(\"PC2 (\", pct_var[2], \"%)\")\n    ) +\n  scale_color_brewer(palette = \"Dark2\", name = \"Infection status\") +\n  scale_shape(name = \"Time points\") +\n  theme_bw() +\n  theme(panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-26-1.png){width=85%}\n:::\n:::\n\n\n\n\n</details>\n:::\n\n## Differential Expression (DE) analysis\n\n### Figuring out how to do the analysis\n\nFirst, let's see how the DE analysis was done in the paper:\n\n> *Then, we used the DESeq2 package (Love et al., 2014) to perform the differential gene expression analysis comparing: (i) P. relictum-infected mosquitoes vs. controls, (ii) P. cathemerium-infected mosquitoes vs. controls, and (iii) P. relictum-infected mosquitoes vs. P. cathemerium-infected mosquitoes.*\n\nThis is not terribly detailed and could be interpreted in a couple of different ways.\nFor example, they may have compared infection statuses by *ignoring* time points\n***or*** by *controlling for* time points in various ways.\n\nIgnoring time would mean analyzing the full dataset (all time points)\nwhile only using the infection status as an independent variable,\ni.e. using the design `~treatment`.\n\n::: exercise\n#### {{< fa user-edit >}} Your Turn\n\nGiven the PCA results, do you think we can ignore the `dpi` variable?\n\n<details><summary>*Click to see the answer*</summary>\nTODO ADD SOLUTION\n</details>\n:::\n\nControlling for time can be done in two ways:\n\n- An analysis with two independent variables (factors): `~ dpi + treatment`\n- Pairwise comparisons between each combination of `dpi` and `treatment`\n\nIf you take a look at Table 1 with the DE results,\nit should become clearer how they did their analysis:\n\n![](../img/paper_table1.png){fig-align=\"center\" width=\"80%\"}\n\n::: exercise\n#### {{< fa user-edit >}} Your Turn\n\nHow do you interpret this: did they run pairwise comparisons or a two-factor model?\n\n<details><summary>*Click to see the answer*</summary>\nIt looks like they performed pairwise comparisons between each combination of\n`dpi` and `treatment`.\n</details>\n:::\n\nThat brings us a step closer,\nbut pairwise comparisons with more than independent variable can (also!) be done\nin two ways (and it's not clear from the paper which they used):\n\n- After **subsetting** the dataset to each combination of dpi and treatment.\n- After creating a single, **combined independent variable** that is a\n  combination of time and treatment.\n\nThe latter method is the more common one, and is what we will use below.\n\n### Setting the statistical design\n\nYou will now create a new variable that is a combination of `treatment` and `dpi`,\nand call it `group`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a combined variable called 'group':\ngroup <- paste(dds$treatment, dds$dpi, sep = \"_\")\n\n# Turn this into a 'factor' and add it to the DESeq2 object:\n# (Factors are a common R data type for categorical variables, and required by DESeq2)\ndds$group <- factor(group)\n```\n:::\n\n\n\n\nTake a look at the variable you created:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds$group\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n [1] control_1      cathemerium_1  relictum_1     control_1      cathemerium_1 \n [6] relictum_1     control_1      cathemerium_1  relictum_1     relictum_1    \n[11] cathemerium_10 relictum_10    control_10     control_10     cathemerium_10\n[16] relictum_10    control_10     cathemerium_10 cathemerium_10 control_10    \n[21] relictum_10    relictum_10   \n6 Levels: cathemerium_1 cathemerium_10 control_1 control_10 ... relictum_10\n```\n\n\n:::\n:::\n\n\n\n\nWhich unique values does `group` have, and how many samples are in each?\nWe can use the `table()` function for this:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dds$group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n\n cathemerium_1 cathemerium_10      control_1     control_10     relictum_1 \n             3              4              3              4              4 \n   relictum_10 \n             4 \n```\n\n\n:::\n:::\n\n\n\n\nNext, set the analysis design:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note: the symbol before 'group' is a tilde, ~ \ndesign(dds) <- ~ group\n```\n:::\n\n\n\n\nPhew, now you're finally ready to run the DE analysis!\n\n### Running the DE analysis\n\nWhile you had to do a lot of prep to get here,\nactually running the DE analysis is very simple.\nIt can be done with the function `DESeq()`,\nand we only need to give it the DESeq2 object,\nsince the analysis options are already specified in the object itself:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# (Note that the output is assigned back to the same `dds` object -\n#  the DE results are added to it)\ndds <- DESeq(dds)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\nestimating size factors\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\nestimating dispersions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\ngene-wise dispersion estimates\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\nmean-dispersion relationship\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\nfinal dispersion estimates\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\nfitting model and testing\n```\n\n\n:::\n:::\n\n\n\n\nThe `DESeq()` function performs three steps consecutively:\n\n1. \"Normalization\" by library size and composition\n2. Estimation of gene-wise variance in counts (\"dispersion\")\n3. Fitting the statistical model (a negative binomial GLM) and\n   calculating the test statistics\n\nA key thing to understand is that above,\nDESeq2 automatically performed **pairwise** comparisons between **each of the (6) levels**\nof the `group` variable.\nThis means that for any individual gene, it tested whether the gene is\ndifferentially expressed *separately for each of these pairwise comparisons*.\n\n_TODO - VISUALIZE THIS?_\n\n## Extracting the DE results\n\nDESeq2 stores the results as a separate table for each pairwise comparison.\nNow, you'll extract one of these tables.\n\n### The results table\n\nYou can extract the results for one pairwise comparison\n(which DESeq2 refers to as a **contrast**) at a time,\nby specifying it with the `contrast` argument as a vector of length 3:\n\n1. The focal independent variable (here, `group`)\n2. The first (reference) level of the independent variable (in the example below, `relictum_1`)\n3. The second level of the independent variable (in the example below, `control_1`)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfocal_contrast <- c(\"group\", \"relictum_1\", \"control_1\")\nres_rc1 <- results(dds, contrast = focal_contrast)\n\nhead(res_rc1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\nlog2 fold change (MLE): group relictum_1 vs control_1 \nWald test p-value: group relictum_1 vs control_1 \nDataFrame with 6 rows and 6 columns\n       baseMean log2FoldChange     lfcSE      stat    pvalue      padj\n      <numeric>      <numeric> <numeric> <numeric> <numeric> <numeric>\nATP6  7658.0445      -0.416305  0.609133 -0.683438 0.4943300  0.776172\nATP8     4.9196      -1.311116  1.388811 -0.944057 0.3451408        NA\nCOX1 75166.8670      -0.590935  0.282075 -2.094958 0.0361747  0.208045\nCOX2  7807.1848      -0.610152  0.578401 -1.054893 0.2914743  0.615249\nCOX3 41037.7359      -0.400173  0.251760 -1.589498 0.1119479  0.388880\nCYTB 36916.6130      -0.501653  0.261927 -1.915242 0.0554617  0.266528\n```\n\n\n:::\n:::\n\n\n\n\nWhat do the columns in this table contain?\n\n- **`baseMean`**: Mean expression level across all samples.\n- **`log2FoldChange`**: The \"log2-fold change\" of gene counts between the compared levels.\n- **`lfcSE`**: The uncertainty in terms of the standard error (SE) of the log2-fold change estimate.\n- **`stat`**: The value for the Wald test's test statistic.\n- **`pvalue`**: The *uncorrected* p-value from the Wald test.\n- **`padj`**: The multiple-testing corrected p-value (i.e., adjusted p-value).\n\n::: callout-note\n#### Multiple testing correction\n\nBecause you are testing significance for *many* genes,\nyou need to correct for multiple testing.\nThis can be done in multiple ways,\nbut DESeq2 uses the Benjamini-Hochberg False Discovery Rate (FDR) correction.\nFor more info, see this [StatQuest video](https://www.youtube.com/watch?v=K8LQSvtjcEo).\n:::\n\n### Log2-fold changes (LFCs)\n\nIn RNA-Seq analysis,\nlog2-fold changes (LFCs) are the standard way of representing the\n**magnitude (*effect size*) of expression level differences**\nbetween two groups of interest.\nWith A and B being the compared sample groups, the LFC is calculated as:\n\n``` bash-out-solo\nlog2(mean of A / mean of B)\n```\n\nDue the log-transformation,\nthe LFC also increase more slowly than a raw fold-change:\n\n- An LFC of **`1`** indicates a 2-fold difference\n- An LFC of **`2`** indicates a 4-fold difference\n- An LFC of **`3`** indicates a 8-fold difference\n\nA nice property of LFC is that decreases and increases in expression are expressed symmetrically:\n\n- An LFC of **`1`** means that group A has a **two-fold higher** expression that group B\n- An LFC of **`-1`** means that group A has a **two-fold lower** expression that group B\n\n### Numbers of differentially expressed genes (DEGs)\n\nHow many adjusted p-values were less than 0.05 -- i.e., significant?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# (We need 'na.rm = TRUE' because some p-values are 'NA')\n# (If we don't remove NAs from the calculation, sum() will just return NA)\nsum(res_rc1$padj < 0.05, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] 801\n```\n\n\n:::\n:::\n\n\n\n\nThis means that you found 801\nDifferentially Expressed Genes (**DEG**s) for this specific pairwise comparison.\n\n::: exercise\n#### {{< fa user-edit >}} Exercise: DEG numbers\n\nThe paper's Table 1 (which we saw above) reports the number of DEGs for a\nvariety of comparisons.\n\n- How does the number of DEGs we just got compare to what they found in the paper\n  for this comparison?\n\n- The table also reports numbers of up- and downregulated genes separately.\n  Can you get those numbers for your DE results?\n\n<details><summary>*Click to see the solution*</summary>\n\n<hr style=\"height:1pt; visibility:hidden;\" />\n\n- Option 1: Solution using tidyverse/dplyr:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First convert the results table into a regular data frame:\nas.data.frame(res_rc1) |>\n  # Then, only select the rows/genes that are significant:\n  filter(padj < 0.05) |>\n  # If you run count() on a logical test, you get the nrs. that are FALSE v. TRUE\n  dplyr::count(log2FoldChange > 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n  log2FoldChange > 0   n\n1              FALSE 616\n2               TRUE 185\n```\n\n\n:::\n:::\n\n\n\n\n- Option 2: Solution using base R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Down-regulated (relictum < control):\nsum(res_rc1$log2FoldChange < 0 & res_rc1$padj < 0.05, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] 616\n```\n\n\n:::\n\n```{.r .cell-code}\n# Up-regulated (relictum > control):\nsum(res_rc1$log2FoldChange > 0 & res_rc1$padj < 0.05, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] 185\n```\n\n\n:::\n:::\n\n\n\n\n</details>\n:::\n\n::: exercise\n#### {{< fa user-edit >}} Bonus exercise: more DEGs\n\n- The table also reports the number of DEGs with an absolute LFC > 1.\n  Can you get those numbers for your DE results?\n\n<details><summary>*Click to see the solution*</summary>\n\n<hr style=\"height:1pt; visibility:hidden;\" />\n\n- Option 1: Solution using tidyverse/dplyr:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First we need to convert the results table into a regular data frame\nas.data.frame(res_rc1) |>\n  # Then we only select the rows/genes that are significant\n  filter(padj < 0.05, abs(log2FoldChange) > 1) |>\n  # If we run count() on a logical test, we get the nrs. that are FALSE v. TRUE\n  dplyr::count(log2FoldChange > 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n  log2FoldChange > 0   n\n1              FALSE 159\n2               TRUE  49\n```\n\n\n:::\n:::\n\n\n\n\n- Option 2: Solution using base R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Down-regulated (relictum < control):\nsum(res_rc1$log2FoldChange < -1 & res_rc1$padj < 0.05, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] 159\n```\n\n\n:::\n\n```{.r .cell-code}\n# Up-regulated (relictum > control):\nsum(res_rc1$log2FoldChange > 1 & res_rc1$padj < 0.05, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] 49\n```\n\n\n:::\n:::\n\n\n\n\n</details>\n\n- Extract the results for one or more other contrasts in the table,\n  and compare the results.\n:::\n\n## DE result visualizations\n\nYou will create a few plots for the `relictum_24h` vs.\n`control_24h` comparison results, which you extracted above.\n\n### Volcano plot\n\nFor a nice overview of the results,\nyou can create a so-called \"volcano plot\" using the `EnhancedVolcano()` function\nfrom the package of the same name\n([see here for a \"vignette\" / tutorial](https://bioconductor.org/packages/release/bioc/vignettes/EnhancedVolcano/inst/doc/EnhancedVolcano.html)):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nEnhancedVolcano(\n  toptable = res_rc1,      # DESeq2 results to plot   \n  title = \"relictum vs. control at 24 hpi\",\n  x = \"log2FoldChange\",     # Plot the log2-fold change along the x-axis\n  y = \"padj\",               # Plot the p-value along the y-axis\n  lab = rownames(res_rc1), # Use the rownames for the gene labels (though see below)\n  labSize = 0               # Omit gene labels for now\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n``` warning-r-output\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\nℹ The deprecated feature was likely used in the EnhancedVolcano package.\n  Please report the issue to the authors.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n``` warning-r-output\nWarning: The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.\nℹ Please use the `linewidth` argument instead.\nℹ The deprecated feature was likely used in the EnhancedVolcano package.\n  Please report the issue to the authors.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-38-1.png){width=85%}\n:::\n:::\n\n\n\n\n::: exercise\n#### {{< fa user-edit >}} Exercise: Interpret the volcano plot\n\nTODO\n\n:::\n\n::: exercise\n#### {{< fa user-edit >}} Bonus Exercise: Improve the Volcano Plot\n\nThe `EnhancedVolcano()` function by default adds gene IDs to highly significant genes,\nbut above, we turned off gene name labeling by setting `labSize = 0`.\nI did this because the default p-value cut-off for point labeling is `1e-5` and in this case,\nthat would make the plot quite busy with gene labels.\nWe might want to try a plot with a stricter p-value cut-off that does show the gene labels.\n\nPlay around with the p-value cut-off and the labeling to create a plot you like.\\\n*Check the*\n[vignette](https://bioconductor.org/packages/release/bioc/vignettes/EnhancedVolcano/inst/doc/EnhancedVolcano.html)\n, *or the help page (accessed by running `?EnhancedVolcano`) to see how you can do this.*\n\n<details><summary>*Click for an example*</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nEnhancedVolcano(\n  toptable = res_rc1,      \n  title = \"relictum vs. control at 24 hpi\",\n  x = \"log2FoldChange\",     \n  y = \"padj\",             \n  lab = rownames(res_rc1), \n  labSize = 4,               # Now we will show the gene labels\n  pCutoff = 10e-10,          # Modify the p-value cut-off\n  subtitle = NULL,           # I'll also remove the silly subtitle\n  caption = NULL,            # ... and the caption\n  )\n```\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-39-1.png){width=85%}\n:::\n:::\n\n\n\n</details>\n:::\n\n::: exercise\n#### {{< fa user-edit >}} Bonus Exercise: Which gene is my outlier?\n\nFigure out the identity of the abovementioned log2-fold change outlier.\\\n*(You can do so either by labeling it in the plot, or by filtering the `res_rc1` table.)*\n\n<details><summary>*Click for the solution on how to label it in the plot*</summary>\n\n<hr style=\"height:1pt; visibility:hidden;\" />\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nEnhancedVolcano(\n  toptable = res_rc1,      \n  title = \"relictum vs. control at 24 hpi\",\n  x = \"log2FoldChange\",     \n  y = \"padj\",             \n  lab = rownames(res_rc1), \n  labSize = 4,               \n  pCutoff = 0.05,            # Modify the p-value cut-off\n  FCcutoff = 20,             # Modify the LFC cut-off\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n``` warning-r-output\nWarning: Removed 1 row containing missing values or values outside the scale range\n(`geom_vline()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-40-1.png){width=85%}\n:::\n:::\n\n\n\n</details>\n\n<details><summary>*Click for the solution on how to find it in the results table*</summary>\n\n<hr style=\"height:1pt; visibility:hidden;\" />\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas.data.frame(res_rc1) |> filter(log2FoldChange > 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n             baseMean log2FoldChange    lfcSE     stat       pvalue\nLOC120431476 39.72038       43.77762 5.301369 8.257795 1.483875e-16\n                     padj\nLOC120431476 3.434281e-13\n```\n\n\n:::\n:::\n\n\n\n\n_(Interestingly, there's a second gene with a LFC \\> 20 that we hadn't seen in the plot,_\n_because it has `NA` as the `pvalue` and `padj`._\n_See the section \"Extra info: `NA` values in the results table\" in the_\n_[Appendix](#appendix-the-de-results) above for why p-values can be set to `NA`.)_\n\n</details>\n:::\n\n### Plot specific genes\n\nIt can also be very informative to look at plots of expression levels for individual\ngenes, especially for those with highly significant differential expression.\n\nLet's plot the single most highly significant DEG.\nWe can get the ID of this gene as follows:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert the results table into a regular dataframe and sort by adjusted p-value:\ntop_df <- data.frame(res_rc1) |> arrange(padj)\n\n# Gene IDs are the row names: extract the first row name to get the gene of interest\ntop1 <- rownames(top_df)[1]\ntop1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n[1] \"LOC120423768\"\n```\n\n\n:::\n:::\n\n\n\n\nLike it does for PCA, DESeq2 also has a gene plotting function.\nThis will by default plot normalized gene counts.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotCounts(dds, gene = top1, intgroup = \"group\")\n```\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-43-1.png){width=100%}\n:::\n:::\n\n\n\n\n::: {.callout-tip appearance=\"simple\"}\nYou may have to drag the right-hand pane in RStudio way to the left in order\nto see all the x-axis labels...\n:::\n\nIn the above plot, we're not just seeing the difference between `relictum_24h` and `control_24h`,\nbut are seeing expression levels for all four treatment-time combinations.\nThat may not always be what you want, but it is useful to see the expression\npatterns across all groups.\n\nHere, the pattern suggests ... TODO\n\n:::: exercise\n#### {{< fa user-edit >}} Exercise: Plot additional DE genes\n\nPlot one or a few more of the top-DE genes.\nDo they have similar expression patterns across treatment and time points as\nthe first one?\n\nTODO ADD SOLUTION\n:::\n\n::: exercise\n#### {{< fa user-edit >}} Bonus exercise: Plot the outlier gene\n\nPlot the gene with the very high LFC value that you saw when making\nthe volcano plot. How would you interpret this result?\n\n<details><summary>*Click to get the ID of the outlier gene*</summary>\nA previous bonus exercise showed you how to find the ID of the outlier gene.\nIt is: `LOC120431476`.\n</details>\n\n<details><summary>*Click for the solution*</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotCounts(dds, gene = \"LOC120431476\", intgroup = \"group\")\n```\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-44-1.png){width=100%}\n:::\n:::\n\n\n\n\nWow! It looks like in every single dpi + treatment combination,\nall but one (or in one case, two) of the samples have zero expression,\nbut there are several extreme outliers.\n\nOur focal comparison is `control_24h` vs. `relictum_24h`,\nand it looks like the difference between these two groups is solely due to the one\noutlier in `relictum`.\nNevertheless, even the multiple-testing corrected p-value (`padj`) is\nsignificant for this gene:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas.data.frame(res_rc1) |>\n  rownames_to_column(\"gene\") |>\n  filter(gene == \"LOC120431476\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n          gene baseMean log2FoldChange    lfcSE     stat       pvalue\n1 LOC120431476 39.72038       43.77762 5.301369 8.257795 1.483875e-16\n          padj\n1 3.434281e-13\n```\n\n\n:::\n:::\n\n\n\n\nSo, you have to be careful with talking these statistical results at face value,\nand need to visualize important genes!\n</details>\n::::\n\n::: exercise\n#### {{< fa user-edit >}} Bonus exercise: Make a better gene expression plot\n\nThe default `plotCounts()` function creates a rather basic plot.\nCustomize the plot with _ggplot2_ to make it better-looking and clearer.\n\n<details><summary>*Solution part 1: getting the dataframe*</summary>\n\nBelow, you'll use that DESeq2 function, but only to extract the counts for our gene\nof interest in a format for plotting, by adding `returnData = TRUE`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use plotCounts with returnData = TRUE just to get a single-gene count table\n# that is suitable for plotting:\nfocal_gene_counts <- plotCounts(\n  dds,\n  gene = top1,\n  intgroup = c(\"dpi\", \"treatment\"),\n  returnData = TRUE\n  )\n\n# Take a look at the resulting dataframe:\nhead(focal_gene_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` styled-output\n                 count dpi   treatment\nERR10802863 1543.81532   1     control\nERR10802864 2279.03704   1 cathemerium\nERR10802865   25.42295   1    relictum\nERR10802866 1105.75009   1     control\nERR10802867 1199.28425   1 cathemerium\nERR10802868   32.14394   1    relictum\n```\n\n\n:::\n:::\n\n\n\n\n</details>\n\n<details><summary>*Solution part 2: Making the plot*</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfocal_gene_counts |>\n  # Treatment along the x-axis, gene counts along the y, color by treatment:\n  ggplot(aes(x = treatment, y = count, fill = treatment)) +\n  # Plot separate \"facets\" with the different time points\n  facet_wrap(vars(dpi)) +\n  # Add a boxplot with a partly transparaent (alpha) color:\n  geom_boxplot(alpha = 0.5, outlier.shape = NA) +\n  # _And_ add individual points:\n  geom_point(\n    size = 4,\n    shape = 21,\n    position = position_jitter(width = 0.1, heigth = 0)\n    ) +\n  # Plot styling (e.g., we don't need a legend)\n  theme_bw() +\n  theme(legend.position = \"none\")\n```\n:::\n\n\n\n</details>\n:::\n\n## In Closing\n\nToday, you have performed several steps in the analysis of gene counts that\nresult from a typical RNA-Seq workflow. Specifically, you have:\n\n- Created a DESEq2 object from the gene count data and the experiment's metadata\n- Performed exploratory data analysis including a PCA\n- Ran a Differential Expression (DE) analysis with DESeq2\n- Extracted, interpreted, and visualized the DE results\n\n#### What would be the next steps in such an analysis?\n\nTypical next steps in such an analysis include:\n\n- Extracting, comparing, and synthesizing DE results across **all pairwise comparisons**\n  (this would for example allow us to make the upset plot in *Figure 2 of the paper*)\n\n- **Functional enrichment analysis** with Gene Ontology (GO) terms,\n  as done in the paper, and/or with KEGG pathways.\n\n<br>\n\n-----\n\n## Appendix\n\n### Exporting the results\n\nYou may be wondering how you can save the DE results tables to files.\nYou can do this with a writing counterpart to `read_tsv()` called, you guessed it,\n`write_tsv()`.\nThis stores the table to a TSV text file, which can be opened in Excel. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write the \nwrite_tsv(as.data.frame(res_rc1), \"DE-results_rc1.tsv\")\n```\n:::\n\n\n\n\n### Heatmaps\n\nRather than plotting expression levels for many individual genes,\nyou can create \"heatmap\" plots to plot dozens (possibly even hundreds) of genes at once.\n\nWe will create heatmaps with the `pheatmap` function,\nand let's make a heatmap for the top-25 most highly significant DEGs for our focal contrast.\n\nFirst, let's install and then load this package:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"pheatmap\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# First load the pheatmap package:\nlibrary(pheatmap)\n```\n:::\n\n\n\n\nUnlike with some of the functions we used before,\nwe unfortunately can't directly use our DESeq2 object,\nbut we have to extract and subset the count matrix,\nand also pass the metadata to the heatmap function:\n\nTODO - FIX THE SAMPLE SORTING \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# You need a normalized count matrix, like for the PCA\n# You can simply extract the matrix from the normalized dds object we created for the PCA\nnorm_mat <- assay(dds_vst)\n\n# In the normalized count matrix, select only the genes of interest\n# We'll create a vector with the top256 most significant DEGs\ntop25_DE <- rownames(top_df)[1:25]\nnorm_mat_sel <- norm_mat[match(top25_DE, rownames(norm_mat)), ]\n\n# Sort the metadata\nmeta_sort <- meta |>\n  arrange(treatment, dpi) |>\n  select(treatment, dpi)\n```\n:::\n\n\n\n\nNow you can create the plot:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npheatmap(\n  norm_mat_sel,\n  annotation_col = meta_sort,  # Add the metadata\n  cluster_cols = FALSE,        # Don't cluster samples (=columns, cols)\n  show_rownames = FALSE,       # Don't show gene names\n  scale = \"row\",               # Perform z-scaling for each gene\n  )\n```\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-52-1.png){width=85%}\n:::\n:::\n\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n- The z-scaling with `scale =` will make sure we can compare genes with\n  very different expression levels: after all,\n  we're interested in relative expression levels across samples/sample groups\n\n- `pheatmap` will by default perform hierarchical clustering both at the sample\n  (`col`) and gene (`row`) level,\n  such that more similar samples and genes will appear closer to each other.\n  Above, we turned clustering off for samples to keep them in their groupwise order.\n:::\n\n::: exercise\n#### {{< fa user-edit >}} Bonus Exercise\n\nMake a heatmap with the top-25 **most-highly expressed** genes\n(i.e., genes with the highest mean expression levels across all samples).\n\n<details><summary>*Click for a hint: how to get that top-25*</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop25_hi <- names(sort(rowMeans(norm_mat), decreasing = TRUE)[1:25])\n```\n:::\n\n\n\n\n</details>\n\n<details><summary>*Click for the solution*</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# In the normalized count matrix, select only the genes of interest\nnorm_mat_sel <- norm_mat[match(top25_hi, rownames(norm_mat)), ]\n\n# Sort the metadata\nmeta_sort <- meta |>\n  arrange(treatment, dpi) |>\n  select(treatment, dpi)\n\n# Create the heatmap\npheatmap(\n  norm_mat_sel,\n  annotation_col = meta_sort,\n  cluster_cols = FALSE,\n  show_rownames = FALSE,\n  scale = \"row\"\n  )\n```\n\n::: {.cell-output-display}\n![](DE_files/figure-html/unnamed-chunk-54-1.png){width=85%}\n:::\n:::\n\n\n\n\n</details>\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}